### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: Bad path: C:\Kohya\kohya_ss\xformers @ https:\github.com\C43H66N12O12S2\stable-diffusion-webui\releases\download\f\xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl

### ISSUE THREAD

**Issue by Kaspur2012** [bmaltais/kohya_ss#176]
hello, I have tried numerous time installing kohya_ss but it always stop at this point:
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 numpy-1.21.6 pillow-9.4.0 requests-2.28.2 torch-1.12.1+cu116 torchvision-0.13.1+cu116 typing-extensions-4.5.0 urllib3-1.26.14
WARNING: You are using pip version 19.2.3, however version 23.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
WARNING: Requirement 'xformers @ https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl' looks like a filename, but the file does not exist
ERROR: Could not install packages due to an EnvironmentError: Bad path: C:\Kohya\kohya_ss\xformers @ https:\github.com\C43H66N12O12S2\stable-diffusion-webui\releases\download\f\xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl

WARNING: You are using pip version 19.2.3, however version 23.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
ERROR: xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 19.2.3, however version 23.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
cp : The filename, directory name, or volume label syntax is incorrect.
At line:11 char:1
+ cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand

cp : Could not find a part of the path 'C:\Kohya\kohya_ss\venv\Lib\site-packages\bitsandbytes\cextension.py'.
At line:12 char:1
+ cp .\bitsandbytes_windows\cextension.py .\venv\Lib\site-packages\bits ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand

cp : Could not find a part of the path 'C:\Kohya\kohya_ss\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py'.
At line:13 char:1
+ cp .\bitsandbytes_windows\main.py .\venv\Lib\site-packages\bitsandbyt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand

accelerate : The term 'accelerate' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:15 char:1
+ accelerate config
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (accelerate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I tried to disable my antivirus and firewall but same error.
any idea?

thanks

**Comment by TurnipLove** [comment]
Were you able to solve this? I am getting stuck on this same problem. :E

**Comment by TurnipLove** [comment]
I think I fixed this for myself by doing the following:

Manually copy the bitsandbytes_windows folder from the kohya_ss directory to kohya_ss\venv\Lib\site-packages then rename that folder to bitsandbytes open that folder and inside create a new folder called cuda_setup drag the file "main.py" into it

in powershell type "pip install accelerate"

now try to install again

I don't really know what I am doing but that seemed to advance me from this problem to another maybe it will help you. GL lol

**Comment by Kaspur2012** [comment]
hello,
I saw that you skip a couple of steps and went to the end and manually moved/copied the files/folder and that should work but the problem still remain sadly that caused by the previous steps.

So I kinda got it working by doing the followings:
-starting from the beginning I just make a brandnew folder named Kohya
-going the powershell stuff according the the instruction - Set-ExecutionPolicy Unrestricted ..etc
-I run the code line by line this time starting with python -m venv venv
.\venv\Scripts\activate
 to activate the python enviroment
- then pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 which went through just fine
- then pip install --use-pep517 --upgrade -r requirements.txt which I encountered a coupe problem:
   - 1st is xformers @ https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl which is I think is our main problem , I decided to remove that line from the req txt file for now...
   - 2nd problem is fairscale==0.4.13 in the req txt which pip said it cannot find v0.4.13 so I decided to use/change v 0.4.2
- after making those changes to the req txt file, it went through just fine, took forever to finish
- then I ran pip install -U -I --no-deps https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl which I encountered something like this machine or module does not support wheel or something I forget so I skip this step
- then I ran these lines : cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
      cp .\bitsandbytes_windows\cextension.py .\venv\Lib\site-packages\bitsandbytes\cextension.py
      cp .\bitsandbytes_windows\main.py .\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py
      which I think you did manually in your reply, they ran just fine
-then accelerate config which ran fine, it asked me a bunch of questions which I answered according to a youtube vid.
-then i exit powershell and ran gui.bat. It ran find and I was able to open the kohya_ss GUI webpage

that is where I am at atm, am fairly certain that I am not using xformer atm so the training maybe alot slower?? or not at all but I had not train anything yet. I'll let you know

thanks

**Comment by profekavendoish** [comment]
I'm still stuck at this step help >D

**Comment by Kaspur2012** [comment]
hello,

So I tried to train earlier and got a few errors which I kinda expected but not wanting. 
Anyhow after a bit of research online, I think I finally found out my problem and it kinda a silly problem...:(

So I had used python before on this machine a long time ago. After I installed Automatic1111 which require python 3.10 which I installed then. Since Automatic1111 is working fine on my machine, I never really think there is anything wrong until I tried to install Koyha_ss. 

It turned out I have multiple version of python(3.7, 3.10) on my machine. Apparently when I installed 3.10, either I didn't followed the instruction or something wasn't checked. Long story short, my default python version is 3.7 NOT 3.10 as required by Koyha_ss. 
You can check you default python version by : python --version in cmd
You can set the default version of python by - https://stackoverflow.com/a/52913040

So now my default python version is 3.10, all the install went through w.o any errors....yay

So I follwed the vid and went ahead and update koyha_ss before I start training....big mistake..for now.. since this last update I think broke kohya_ss training. I got the following error now: AttributeError: 'Namespace' object has no attribute 'noise_offset'

which there are a few other ppl who has this problem yesterday so at least I didn't break anything...yet. 

Anyhow, i'll await till they fix this problem

hope this helps, 
cheers

**Comment by theseraphim** [comment]
anyone stuck on this... theres a good chance your venv folder is not in the kohya_ss folder, and therefore its not working, copy the venv folder into the kohya folder,
