### ISSUE TITLE
learning_rate_te2 must be given as 0

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1992]
Currently when we set Text Encoder rate as 0, the GUI is not providing it

Kohya said it has to be provided

SDXL training separate text encoder Learning rates for TE1 and TE2

https://github.com/kohya-ss/sd-scripts/issues/1131#issuecomment-1958970410

**Comment by FurkanGozukara** [comment]
yep i verified this bug exists and breaks my config :/

**Comment by bmaltais** [comment]
Hummm, this should be an easy fix. I will address it in the dev branch.

**Comment by bmaltais** [comment]
I am loking at the code in the master branch and it should work. Have you tried pulling the latest version I published this morning?

**Comment by FurkanGozukara** [comment]
> I am loking at the code in the master branch and it should work. Have you tried pulling the latest version I published this morning?

I just did a git pull on master and no still not showing

v 22.6.2

 there is also new high vram option you plan to add? thank you

**Comment by bmaltais** [comment]
Can you share a json config file that trigger the issue?

**Comment by FurkanGozukara** [comment]
> Can you share a json config file that trigger the issue? And that is is (Lora, dreambooth, fine tune)

sure here it is

it is dreambooth sdxl

[48GB_TextEncoder (1).json.txt](https://github.com/bmaltais/kohya_ss/files/14394827/48GB_TextEncoder.1.json.txt)

**Comment by bmaltais** [comment]
Found the source of the issue. Should be fixed in next release. FOr now you can text in the dev-pure branch.
