### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by llm8047** [bmaltais/kohya_ss#3136]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 760, in __call__
    await self.app(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 427, in main
    gradio_api_info = api_info(False)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 456, in api_info
    app.api_info = app.get_blocks().get_api_info()
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2849, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 947, in _json_schema_to_python_type
    des = [
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/data/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 863, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable

**Comment by TheElevatedOne** [comment]
I have found this, cloned the branch and the same error occurrs. Had the issue in both **master** and **sd3-flux.1**.

**Comment by bmaltais** [comment]
Try switching to master and pull the latest version. THe issue should be fixed:

- Upgrade Gradio, diffusers and huggingface-hub to latest release to fix issue with ASGI.
- Add a new method to setup and run the GUI. You will find two new script for both Windows (gui-uv.bat) and Linux (gui-uv.sh). With those scripts there is no need to run setup.bat or setup.sh anymore.

**Comment by TheElevatedOne** [comment]
Thanks, work amazingly again.

**Comment by oceanus52** [comment]
this still isn't working even after getting the updated repository for flux

![Image](https://github.com/user-attachments/assets/645fec1c-2111-4633-a889-809b37cd9ad9)

![Image](https://github.com/user-attachments/assets/6a85e246-03c1-40d3-aa67-b34858e550e8)

**Comment by oceanus52** [comment]
this script is still having issues.  I'm using runpod and try to install using the ./gui-uv.sh and its not working. I'm still having to use the ./setup-runpod.sh script and sometimes have to install things in the venv afterwards.  the gradio is still giving the same error even with the updated requirements.  I started fresh and the scripts just aren't working as is.

![Image](https://github.com/user-attachments/assets/174ef057-ad86-4dc7-82ef-0ccfbe7a849f)

![Image](https://github.com/user-attachments/assets/9a7bbde1-e383-482c-b6aa-15c206d51bdf)

![Image](https://github.com/user-attachments/assets/adaf8a5d-e211-474e-8981-cb6361953bf0)

**Comment by oceanus52** [comment]
After restarting the pod a couple of times and force updating gradio both in and out of venv, I ran the gui script again which just downgraded gradio again.  However this time it finally ran.  Since I'm not really good with python its hard for me to find out which dependency is causing the issue because it just goes through this cycle of upgrading and downgrading dependencies.  

![Image](https://github.com/user-attachments/assets/d78ac0c5-846c-4f4b-8d20-ee5b9b87fc33)

 ______                 ______            _
(_____ \               (_____ \          | |
 _____) ) _   _  ____   _____) )___    __| |
|  __  / | | | ||  _ \ |  ____// _ \  / _  |
| |  \ \ | |_| || | | || |    | |_| |( (_| |
|_|   |_||____/ |_| |_||_|     \___/  \____|

For detailed documentation and guides, please visit:
https://docs.runpod.io/ and https://blog.runpod.io/


root@2fd1595c24ca:/workspace/kohya_ss# ./gui.sh --server_port 7860 --listen=0.0.0.0 --headless
2025-03-30 02:05:41.349329: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-30 02:05:41.389212: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-30 02:05:41.389254: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-30 02:05:41.389291: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-30 02:05:41.399267: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-30 02:05:41.399622: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-30 02:05:45.794422: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
02:06:09-398865 INFO     Kohya_ss GUI version: v25.0.2                                                                                                                                 
                                                                                                                                                                                       
02:06:09-570644 INFO     Submodule initialized and updated.                                                                                                                            
02:06:09-574744 INFO     nVidia toolkit detected                                                                                                                                       
02:06:14-931375 INFO     Torch 2.5.0+cu124                                                                                                                                             
02:06:15-078431 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100                                                                                                                   
02:06:15-100444 INFO     Torch detected GPU: NVIDIA A40 VRAM 45515MB Arch 8.6 Cores 84                                                                                                 
02:06:15-102609 INFO     Python version is 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]                                                                                          
02:06:15-108386 INFO     Installing/Validating requirements from /workspace/kohya_ss/requirements_runpod.txt...                                                                        
02:06:17-344173 INFO     Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124                                                                           
02:06:17-347166 INFO     Obtaining file:///workspace/kohya_ss/sd-scripts (from -r /workspace/kohya_ss/requirements.txt (line 38))                                                      
02:06:17-350933 INFO     Preparing metadata (setup.py): started                                                                                                                        
02:06:18-567185 INFO     Preparing metadata (setup.py): finished with status 'done'                                                                                                    
02:06:21-595363 INFO     Installing collected packages: library                                                                                                                        
02:06:21-598909 INFO     Attempting uninstall: library                                                                                                                                 
02:06:21-602101 INFO     Found existing installation: library 0.0.0                                                                                                                    
02:06:21-622614 INFO     Uninstalling library-0.0.0:                                                                                                                                   
02:06:31-215308 INFO     Successfully uninstalled library-0.0.0                                                                                                                        
02:06:31-219112 INFO     Running setup.py develop for library                                                                                                                          
02:06:34-112565 INFO     Successfully installed library-0.0.0                                                                                                                          
02:06:34-544703 INFO     headless: True                                                                                                                                                
02:06:34-561308 INFO     Using shell=True when running external commands...                                                                                                            
* Running on local URL:  http://0.0.0.0:7860
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 555, in main
    gradio_api_info = api_info(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 585, in api_info
    api_info = utils.safe_deepcopy(app.get_blocks().get_api_info())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2999, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 931, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 985, in _json_schema_to_python_type
    des = [
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 986, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 993, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 939, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 898, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 555, in main
    gradio_api_info = api_info(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 585, in api_info
    api_info = utils.safe_deepcopy(app.get_blocks().get_api_info())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2999, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 931, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 985, in _json_schema_to_python_type
    des = [
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 986, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 993, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 939, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 898, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 555, in main
    gradio_api_info = api_info(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 585, in api_info
    api_info = utils.safe_deepcopy(app.get_blocks().get_api_info())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2999, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 931, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 985, in _json_schema_to_python_type
    des = [
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 986, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 993, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 939, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 898, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 555, in main
    gradio_api_info = api_info(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 585, in api_info
    api_info = utils.safe_deepcopy(app.get_blocks().get_api_info())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2999, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 931, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 985, in _json_schema_to_python_type
    des = [
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 986, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 993, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 939, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 898, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 555, in main
    gradio_api_info = api_info(request)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 585, in api_info
    api_info = utils.safe_deepcopy(app.get_blocks().get_api_info())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2999, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 931, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 985, in _json_schema_to_python_type
    des = [
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 986, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 993, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 939, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 898, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
╭───────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────╮
│ /workspace/kohya_ss/kohya_gui.py:156 in <module>                                                                                                                                    │
│                                                                                                                                                                                     │
│   155     # Launch the UI with the provided arguments                                                                                                                               │
│ ❱ 156     UI(**vars(args))                                                                                                                                                          │
│   157                                                                                                                                                                               │
│                                                                                                                                                                                     │
│ /workspace/kohya_ss/kohya_gui.py:111 in UI                                                                                                                                          │
│                                                                                                                                                                                     │
│   110     # Launch the Gradio interface with the specified parameters                                                                                                               │
│ ❱ 111     ui_interface.launch(**launch_params)                                                                                                                                      │
│   112                                                                                                                                                                               │
│                                                                                                                                                                                     │
│ /workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py:2627 in launch                                                                                               │
│                                                                                                                                                                                     │
│   2626         ):                                                                                                                                                                   │
│ ❱ 2627             raise ValueError(                                                                                                                                                │
│   2628                 "When localhost is not accessible, a shareable link must be created. Ple                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
root@2fd1595c24ca:/workspace/kohya_ss# source ./venv/bin/activate
(venv) root@2fd1595c24ca:/workspace/kohya_ss# pip install -U gradio
Requirement already satisfied: gradio in ./venv/lib/python3.10/site-packages (5.14.0)
Collecting gradio
  Downloading gradio-5.23.1-py3-none-any.whl (51.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 MB 55.9 MB/s eta 0:00:00
Requirement already satisfied: semantic-version~=2.0 in ./venv/lib/python3.10/site-packages (from gradio) (2.10.0)
Requirement already satisfied: orjson~=3.0 in ./venv/lib/python3.10/site-packages (from gradio) (3.10.16)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in ./venv/lib/python3.10/site-packages (from gradio) (0.13.2)
Requirement already satisfied: python-multipart>=0.0.18 in ./venv/lib/python3.10/site-packages (from gradio) (0.0.20)
Requirement already satisfied: uvicorn>=0.14.0 in ./venv/lib/python3.10/site-packages (from gradio) (0.34.0)
Requirement already satisfied: markupsafe<4.0,>=2.0 in ./venv/lib/python3.10/site-packages (from gradio) (2.1.5)
Collecting gradio-client==1.8.0
  Downloading gradio_client-1.8.0-py3-none-any.whl (322 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 KB 101.9 MB/s eta 0:00:00
Requirement already satisfied: httpx>=0.24.1 in ./venv/lib/python3.10/site-packages (from gradio) (0.28.1)
Requirement already satisfied: ffmpy in ./venv/lib/python3.10/site-packages (from gradio) (0.5.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in ./venv/lib/python3.10/site-packages (from gradio) (0.115.12)
Requirement already satisfied: starlette<1.0,>=0.40.0 in ./venv/lib/python3.10/site-packages (from gradio) (0.46.1)
Requirement already satisfied: pandas<3.0,>=1.0 in ./venv/lib/python3.10/site-packages (from gradio) (2.2.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in ./venv/lib/python3.10/site-packages (from gradio) (0.1.6)
Requirement already satisfied: pydub in ./venv/lib/python3.10/site-packages (from gradio) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in ./venv/lib/python3.10/site-packages (from gradio) (4.13.0)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from gradio) (24.2)
Requirement already satisfied: aiofiles<24.0,>=22.0 in ./venv/lib/python3.10/site-packages (from gradio) (23.2.1)
Collecting groovy~=0.1
  Downloading groovy-0.1.2-py3-none-any.whl (14 kB)
Requirement already satisfied: pydantic>=2.0 in ./venv/lib/python3.10/site-packages (from gradio) (2.11.1)
Requirement already satisfied: typer<1.0,>=0.12 in ./venv/lib/python3.10/site-packages (from gradio) (0.15.2)
Requirement already satisfied: numpy<3.0,>=1.0 in ./venv/lib/python3.10/site-packages (from gradio) (1.26.4)
Requirement already satisfied: pyyaml<7.0,>=5.0 in ./venv/lib/python3.10/site-packages (from gradio) (6.0.2)
Requirement already satisfied: jinja2<4.0 in ./venv/lib/python3.10/site-packages (from gradio) (3.1.6)
Requirement already satisfied: pillow<12.0,>=8.0 in ./venv/lib/python3.10/site-packages (from gradio) (11.1.0)
Collecting huggingface-hub>=0.28.1
  Downloading huggingface_hub-0.29.3-py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 169.1 MB/s eta 0:00:00
Requirement already satisfied: anyio<5.0,>=3.0 in ./venv/lib/python3.10/site-packages (from gradio) (4.9.0)
Requirement already satisfied: ruff>=0.9.3 in ./venv/lib/python3.10/site-packages (from gradio) (0.11.2)
Requirement already satisfied: websockets<16.0,>=10.0 in ./venv/lib/python3.10/site-packages (from gradio-client==1.8.0->gradio) (14.2)
Requirement already satisfied: fsspec in ./venv/lib/python3.10/site-packages (from gradio-client==1.8.0->gradio) (2025.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in ./venv/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio) (1.2.2)
Requirement already satisfied: idna>=2.8 in ./venv/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in ./venv/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in ./venv/lib/python3.10/site-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in ./venv/lib/python3.10/site-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in ./venv/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in ./venv/lib/python3.10/site-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: typing-inspection>=0.4.0 in ./venv/lib/python3.10/site-packages (from pydantic>=2.0->gradio) (0.4.0)
Requirement already satisfied: pydantic-core==2.33.0 in ./venv/lib/python3.10/site-packages (from pydantic>=2.0->gradio) (2.33.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./venv/lib/python3.10/site-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: click>=8.0.0 in ./venv/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in ./venv/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in ./venv/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.1)
Requirement already satisfied: mdurl~=0.1 in ./venv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Installing collected packages: groovy, huggingface-hub, gradio-client, gradio
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.25.2
    Uninstalling huggingface-hub-0.25.2:
      Successfully uninstalled huggingface-hub-0.25.2
  Attempting uninstall: gradio-client
    Found existing installation: gradio_client 1.7.0
    Uninstalling gradio_client-1.7.0:
      Successfully uninstalled gradio_client-1.7.0
  Attempting uninstall: gradio
    Found existing installation: gradio 5.14.0
    Uninstalling gradio-5.14.0:
      Successfully uninstalled gradio-5.14.0
Successfully installed gradio-5.23.1 gradio-client-1.8.0 groovy-0.1.2 huggingface-hub-0.29.3
(venv) root@2fd1595c24ca:/workspace/kohya_ss# dir
Dockerfile   bin                   docs        gui.sh        localizations   pyvenv.cfg                     requirements_macos_amd64.txt      setup            setup.ps1
LICENSE.md   config\ example.toml  examples    include       logs            requirements.txt               requirements_macos_arm64.txt      setup-3.10.bat   setup.sh
README.md    config_files          gui-uv.bat  kohya_gui     models          requirements_linux.txt         requirements_pytorch_windows.txt  setup-runpod.sh  test
SECURITY.md  dataset               gui-uv.sh   kohya_gui.py  outputs         requirements_linux_docker.txt  requirements_runpod.txt           setup-uv.bat     tools
_typos.toml  deprecated            gui.bat     lib           presets         requirements_linux_ipex.txt    requirements_windows.txt          setup.bat        uv.lock
assets       docker-compose.yaml   gui.ps1     lib64         pyproject.toml  requirements_linux_rocm.txt    sd-scripts                        setup.log        venv
(venv) root@2fd1595c24ca:/workspace/kohya_ss# deactivate
root@2fd1595c24ca:/workspace/kohya_ss# ./gui.sh --server_port 7860 --listen=0.0.0.0 --headless
2025-03-30 02:08:55.587004: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-30 02:08:55.625417: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-30 02:08:55.625455: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-30 02:08:55.625495: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-30 02:08:55.635140: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-30 02:08:55.635347: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-30 02:09:00.200625: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
02:09:23-867347 INFO     Kohya_ss GUI version: v25.0.2                                                                                                                                 
                                                                                                                                                                                       
02:09:24-049166 INFO     Submodule initialized and updated.                                                                                                                            
02:09:24-053309 INFO     nVidia toolkit detected                                                                                                                                       
02:09:29-629246 INFO     Torch 2.5.0+cu124                                                                                                                                             
02:09:29-767156 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100                                                                                                                   
02:09:29-789581 INFO     Torch detected GPU: NVIDIA A40 VRAM 45515MB Arch 8.6 Cores 84                                                                                                 
02:09:29-791300 INFO     Python version is 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]                                                                                          
02:09:29-793526 INFO     Installing/Validating requirements from /workspace/kohya_ss/requirements_runpod.txt...                                                                        
02:09:31-959868 INFO     Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124                                                                           
02:09:31-962655 INFO     Obtaining file:///workspace/kohya_ss/sd-scripts (from -r /workspace/kohya_ss/requirements.txt (line 38))                                                      
02:09:31-966325 INFO     Preparing metadata (setup.py): started                                                                                                                        
02:09:33-191276 INFO     Preparing metadata (setup.py): finished with status 'done'                                                                                                    
02:09:33-891794 INFO     Collecting huggingface-hub==0.25.2                                                                                                                            
02:09:34-033680 INFO     Downloading huggingface_hub-0.25.2-py3-none-any.whl (436 kB)                                                                                                  
02:09:34-137213 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 436.6/436.6 KB 4.4 MB/s eta 0:00:00                                                                                  
02:09:35-968378 INFO     Collecting gradio>=5.14.0                                                                                                                                     
02:09:35-972221 INFO     Downloading gradio-5.23.0-py3-none-any.whl (51.3 MB)                                                                                                          
02:09:36-302094 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 MB 74.6 MB/s eta 0:00:00                                                                                   
02:09:36-435575 INFO     Downloading gradio-5.22.0-py3-none-any.whl (46.2 MB)                                                                                                          
02:09:36-840647 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 47.6 MB/s eta 0:00:00                                                                                   
02:09:36-941429 INFO     Downloading gradio-5.21.0-py3-none-any.whl (46.2 MB)                                                                                                          
02:09:37-224905 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 82.7 MB/s eta 0:00:00                                                                                   
02:09:37-326848 INFO     Downloading gradio-5.20.1-py3-none-any.whl (62.3 MB)                                                                                                          
02:09:37-714571 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 64.9 MB/s eta 0:00:00                                                                                   
02:09:37-843964 INFO     Downloading gradio-5.20.0-py3-none-any.whl (62.3 MB)                                                                                                          
02:09:38-545780 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 57.3 MB/s eta 0:00:00                                                                                   
02:09:38-676348 INFO     Downloading gradio-5.19.0-py3-none-any.whl (62.3 MB)                                                                                                          
02:09:39-134215 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 62.6 MB/s eta 0:00:00                                                                                   
02:09:39-262599 INFO     Downloading gradio-5.18.0-py3-none-any.whl (62.3 MB)                                                                                                          
02:09:39-882479 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 70.4 MB/s eta 0:00:00                                                                                   
02:09:40-011596 INFO     Downloading gradio-5.17.1-py3-none-any.whl (62.3 MB)                                                                                                          
02:09:40-681118 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 23.0 MB/s eta 0:00:00                                                                                   
02:09:41-190807 INFO     Collecting gradio-client==1.7.1                                                                                                                               
02:09:41-194620 INFO     Downloading gradio_client-1.7.1-py3-none-any.whl (321 kB)                                                                                                     
02:09:41-198512 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.0/322.0 KB 143.3 MB/s eta 0:00:00                                                                                
02:09:41-220968 INFO     Collecting gradio>=5.14.0                                                                                                                                     
02:09:41-227021 INFO     Downloading gradio-5.17.0-py3-none-any.whl (62.3 MB)                                                                                                          
02:09:41-637230 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 63.3 MB/s eta 0:00:00                                                                                   
02:09:41-768274 INFO     Downloading gradio-5.16.2-py3-none-any.whl (62.2 MB)                                                                                                          
02:09:42-310941 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 68.4 MB/s eta 0:00:00                                                                                   
02:09:42-439807 INFO     Downloading gradio-5.16.1-py3-none-any.whl (62.2 MB)                                                                                                          
02:09:42-829439 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 65.4 MB/s eta 0:00:00                                                                                   
02:09:42-957229 INFO     Downloading gradio-5.16.0-py3-none-any.whl (62.2 MB)                                                                                                          
02:09:43-772765 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 67.1 MB/s eta 0:00:00                                                                                   
02:09:43-924726 INFO     Downloading gradio-5.15.0-py3-none-any.whl (57.8 MB)                                                                                                          
02:09:44-287744 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 MB 67.9 MB/s eta 0:00:00                                                                                   
02:09:44-409497 INFO     Downloading gradio-5.14.0-py3-none-any.whl (57.7 MB)                                                                                                          
02:09:44-780372 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 MB 66.0 MB/s eta 0:00:00                                                                                   
02:09:44-907415 INFO     Collecting gradio-client==1.7.0                                                                                                                               
02:09:44-911246 INFO     Downloading gradio_client-1.7.0-py3-none-any.whl (321 kB)                                                                                                     
02:09:44-914815 INFO     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 321.9/321.9 KB 149.8 MB/s eta 0:00:00                                                                                
02:09:46-933440 INFO     Installing collected packages: library, huggingface-hub, gradio-client, gradio                                                                                
02:09:46-937400 INFO     Attempting uninstall: library                                                                                                                                 
02:09:46-941104 INFO     Found existing installation: library 0.0.0                                                                                                                    
02:09:46-957246 INFO     Uninstalling library-0.0.0:                                                                                                                                   
02:09:56-553691 INFO     Successfully uninstalled library-0.0.0                                                                                                                        
02:09:56-557572 INFO     Running setup.py develop for library                                                                                                                          
02:09:58-740509 INFO     Attempting uninstall: huggingface-hub                                                                                                                         
02:09:58-746249 INFO     Found existing installation: huggingface-hub 0.29.3                                                                                                           
02:09:59-953665 INFO     Uninstalling huggingface-hub-0.29.3:                                                                                                                          
02:09:59-976444 INFO     Successfully uninstalled huggingface-hub-0.29.3                                                                                                               
02:10:01-751040 INFO     Attempting uninstall: gradio-client                                                                                                                           
02:10:01-756201 INFO     Found existing installation: gradio_client 1.8.0                                                                                                              
02:10:01-875880 INFO     Uninstalling gradio_client-1.8.0:                                                                                                                             
02:10:01-884337 INFO     Successfully uninstalled gradio_client-1.8.0                                                                                                                  
02:10:02-221735 INFO     Attempting uninstall: gradio                                                                                                                                  
02:10:02-226684 INFO     Found existing installation: gradio 5.23.1                                                                                                                    
02:10:09-056442 INFO     Uninstalling gradio-5.23.1:                                                                                                                                   
02:10:09-773972 INFO     Successfully uninstalled gradio-5.23.1                                                                                                                        
02:10:30-358761 INFO     Successfully installed gradio-5.14.0 gradio-client-1.7.0 huggingface-hub-0.25.2 library-0.0.0                                                                 
02:10:30-895589 INFO     headless: True                                                                                                                                                
02:10:30-911191 INFO     Using shell=True when running external commands...                                                                                                            
* Running on local URL:  http://0.0.0.0:7860

**Comment by oceanus52** [comment]
I used the old setup scripts first and same ASGI error.  Thats why I came here looking for a solution.

For some reason force upgrading gradio (to like 5.23) and then running the gui.sh script again worked even though it just downgraded gradio during the setup of the script.

Somebody else noted changing the gradio util file might be helpful but I haven't tried it yet.

**Comment by oceanus52** [comment]
nevermind, the flux version was merged with the main version and the dependencies seem to be fixed for now
