### ISSUE TITLE
No module named 'library' when use BLIP Captioning

### ISSUE THREAD

**Issue by zhaojigang** [bmaltais/kohya_ss#510]
I'm getting the following error when i use BLIP Captioning.

Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Captioning files in D:/project/stable-diffusion-trainer/trainer-images/liyitong/image/brime512512...
./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "D:/project/stable-diffusion-trainer/trainer-images/liyitong/image/brime512512" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
Traceback (most recent call last):
  File "D:\project\stable-diffusion-trainer\kohya_ss\finetune\make_captions.py", line 14, in <module>
    import library.train_util as train_util
ModuleNotFoundError: No module named 'library'
...captioning done

i run upgrade.ps1, not work;
 i reinstalled kohya_ss,but it not work; 
i remove venv,then reinstall,but also not work; 
and i use https://github.com/bmaltais/kohya_ss/issues/49 this way , also not work

**Comment by bmaltais** [comment]
Not sure why it suddenly stopped working. I had to fix a similar issue with wd14 yesterday. I will do the same treatment to BLIP I guess...

**Comment by PsychoSmiley** [comment]
Same error for lora extraction "ModuleNotFoundError: No module named 'library'"

**Comment by bmaltais** [comment]
I will have to find what triggered this issue... I have no idea but something must be causing this widespread error... Strange 🤔

**Comment by adrianlungu** [comment]
Ran into this due to the missing `__init__.py` file in the `library` folder. 

Not sure how the others ended up in this state, but in my case, I wanted to test some changes for a file inside the `library` thus I used 

```
python setup.py clean --all
```

to clean the `build` folder. 

However, using `setup.py` afterwards would not work as expected. `find_packages` would not find `library` due to the missing `__init__.py` file. Read something interesting about this [here](https://stackoverflow.com/questions/61503299/does-setuptools-find-packages-require-init-py-files-or-not-to-recognize-pac) and added an empty init file and then `setup.py` and `pip install --upgrade -r requirements.txt` properly created the build and installed the library module and it started working again. 

I saw that the `__init__.py` file is set in `.gitignore` for the library folder but I'm not sure why.

**Comment by bmaltais** [comment]
It is fixed in the latest release. Sorry about that.

**Comment by BaltasarOrtiz** [comment]
I upgraded to the latest version (v21.4.0) but I still get the same error. I also reinstalled and execute the update.bat, but I got no solution. I would like to know if anyone got the same error after updating it.

All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Captioning files in C:\Users\Baltasar\Pictures\quickstart\fenrir\lora\img\100_fenrir...
./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "C:\Users\Baltasar\Pictures\quickstart\fenrir\lora\img\100_fenrir" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
Traceback (most recent call last):
  File "C:\Users\Baltasar\Pictures\kohya\kohya_ss\finetune\make_captions.py", line 14, in <module>
    import library.train_util as train_util
ModuleNotFoundError: No module named 'library'
...captioning done

**Comment by elchupacabrinski** [comment]
yeah I got the same issue on MacOS though

**Comment by adrianlungu** [comment]
If anyone wants to give my solution a try and let me know how it goes ? 

I've committed it over here: https://github.com/adrianlungu/kohya_ss/tree/fix_library_module_missing

Only included the `rebuild.ps1` script for powershell, which you can simply run from the terminal ( ` ./rebuild.ps1` ), for MacOS something like this should work:

```bash
# Activate the virtual environment
source venv/bin/activate

# Clean python build folders
python setup.py clean --all

# Build python modules/packages
python setup.py build

# Upgrade the required packages
pip install --upgrade -r requirements.txt
```

**Comment by elchupacabrinski** [comment]
> ```shell
> pip install --upgrade -r requirements.txt
> ```



> If anyone wants to give my solution a try and let me know how it goes ?
> 
> I've committed it over here: https://github.com/adrianlungu/kohya_ss/tree/fix_library_module_missing
> 
> Only included the `rebuild.ps1` script for powershell, which you can simply run from the terminal ( ` ./rebuild.ps1` ), for MacOS something like this should work:
> 
> ```shell
> # Activate the virtual environment
> source venv/bin/activate
> 
> # Clean python build folders
> python setup.py clean --all
> 
> # Build python modules/packages
> python setup.py build
> 
> # Upgrade the required packages
> pip install --upgrade -r requirements.txt
> ```

Just tried it, didn't work unfortunately

**Comment by bmaltais** [comment]
Is the __init.py__ file in the library folder?

The latest commit should have brought it back and fixed the library issue with it.

**Comment by BaltasarOrtiz** [comment]
I cannot find that file in the library folder. @adrianlungu commented the following: "I saw that the `__init__.py` file is set to `.gitignore` for the library folder but I'm not sure why". The file may not have been uploaded when you did the commit?

**Comment by bmaltais** [comment]
OK, I think it is now fixed. Saw that bad entry in .gitignore

Latest release should have the file back

**Comment by BaltasarOrtiz** [comment]
Now it's working fine, at least for me.

**Comment by zhaojigang** [comment]
thanks,  it's working fine.

**Comment by potatoker** [comment]
I still get the error even if the __init__.py can be found in the library directory. And I'm using the docker build by the dockerfile in the git repo, anyone can help with this?

**Comment by AI-Underdog** [comment]
same here

**Comment by kieranxsomer** [comment]
Ok for us SDXL nerds i had some help with this in the command line this is how mine looked and it worked to get to this point: python  ./finetune/merge_captions_to_metadata.py dataset/Osea_XL/images_new 'dataset/Osea_XL/images_new/meta-cap.json' --caption_extension .txt

Got that part done, so while the library isn't found you CAN still do it via this.

**Comment by darthjaja6** [comment]
Same here

**Comment by rpfile** [comment]
try adding:

parentddir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir))
sys.path.append(parentddir)

right before

import library.train_util as train_util

in make_captions.py

don't know enough about python to say if this is necessary to find a library one directory up or not, but it seems to work.

**Comment by AsaTyr2018** [comment]
> try adding:
> 
> parentddir = os.path.abspath(os.path.join(os.path.dirname(**file**), os.path.pardir)) sys.path.append(parentddir)
> 
> right before
> 
> import library.train_util as train_util
> 
> in make_captions.py
> 
> don't know enough about python to say if this is necessary to find a library one directory up or not, but it seems to work.

i tried it and it failed wit hthe same error.

**Comment by rpfile** [comment]
do you have a folder called library in your installation directory? there are other threads here with similar solutions to the one i posted, do a search of issues with the keyword library.

**Comment by OnePawProductions** [comment]
I got this error after moving my Kohya folder to a different file location post-installation and setup. Once I moved it back to the old location, the error no longer happened.
